In [50]:
from numpy import genfromtxt
import numpy as np

## Part 1

In [49]:
empdat = genfromtxt("DS1_C4_S1_Employee_Data_Challenge.csv", delimiter = ",", dtype = int, skip_header = 1)

In [51]:
# task 1 average age of all employees

avage = np.mean(empdat[:, 1])
print(avage)

28.26


In [52]:
# task 2 employees with age > 25 with total number

totem = np.where(empdat[:,1] > 25)
print('total number employees with age greater than 25 = ', np.size(totem))
print('List of employees with age greater than 25 \n', empdat[totem])

total number employees with age greater than 25 =  38
List of employees with age greater than 25 
 [[ 2 27]
 [ 3 31]
 [ 4 29]
 [ 5 27]
 [ 6 26]
 [ 7 27]
 [ 9 27]
 [10 32]
 [11 28]
 [12 27]
 [14 27]
 [15 35]
 [16 33]
 [17 28]
 [20 27]
 [21 37]
 [22 27]
 [24 27]
 [25 28]
 [26 26]
 [27 27]
 [28 27]
 [29 29]
 [30 49]
 [31 26]
 [32 32]
 [33 26]
 [37 28]
 [38 28]
 [40 26]
 [41 32]
 [42 35]
 [43 33]
 [44 31]
 [45 30]
 [46 36]
 [49 32]
 [50 34]]


In [31]:
# task 3  employee age => 35 > age > 30

age35 = np.where((empdat[:, 1] > 30) & (empdat[:, 1] < 35))
print('Employees with age greater than 30 but less than 35 \n', empdat[age35])

Employees with age greater than 30 but less than 35 
 [[ 3 31]
 [10 32]
 [16 33]
 [32 32]
 [41 32]
 [43 33]
 [44 31]
 [49 32]
 [50 34]]


## part 2

In [53]:
cusdat = genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv', delimiter = ',', skip_header = 1, dtype = int)

In [55]:
# task 1 customers with spending scores greater than 80

spscore = np.where(cusdat[0:, 3] > 80)
print('These are the customers with spending scores greater than 80 \n',cusdat[spscore])

These are the customers with spending scores greater than 80 
 [[  2  21  15  81]
 [  8  23  18  94]
 [ 12  35  19  99]
 [ 20  35  23  98]
 [ 26  29  28  82]
 [ 30  23  29  87]
 [ 34  18  33  92]
 [ 36  21  33  81]
 [ 42  24  38  92]
 [124  39  69  91]
 [128  40  71  95]
 [136  29  73  88]
 [142  32  75  93]
 [144  32  76  87]
 [146  28  77  97]
 [150  34  78  90]
 [152  39  78  88]
 [156  27  78  89]
 [162  29  79  83]
 [164  31  81  93]
 [168  33  86  95]
 [174  36  87  92]
 [176  30  88  86]
 [180  35  93  90]
 [182  32  97  86]
 [184  29  98  88]
 [186  30  99  97]
 [190  36 103  85]
 [194  38 113  91]
 [200  30 137  83]]


In [64]:
# task 2 rows with age between 20 and 24

cus = np.where((cusdat[0:, 1] >= 20) & (cusdat[0:, 1] <= 24))
print('Rows with age bweteen 20 and 24 \n', cusdat[cus,0:])

Rows with age bweteen 20 and 24 
 [[[  2  21  15  81]
  [  3  20  16   6]
  [  4  23  16  77]
  [  6  22  17  76]
  [  8  23  18  94]
  [ 14  24  20  77]
  [ 16  22  20  79]
  [ 18  20  21  66]
  [ 30  23  29  87]
  [ 32  21  30  73]
  [ 36  21  33  81]
  [ 40  20  37  75]
  [ 42  24  38  92]
  [ 46  24  39  65]
  [ 79  23  54  52]
  [ 85  21  54  57]
  [ 88  22  57  55]
  [ 96  24  60  52]
  [100  20  61  49]
  [101  23  62  41]
  [106  21  62  42]
  [125  23  70  29]
  [135  20  73   5]]]


In [71]:
# task 3 lowest and highest annual income

minin = np.where(cusdat[:,2] == (min(cusdat[:, 2])))
maxin = np.where(cusdat[:, 2] == (max(cusdat[:, 2])))

print("Lowest annual income  \n ", cusdat[minin,0:3:2])
print("_______________________________________________________________")
print("Highest annual income  \n", cusdat[maxin, 0:3:2])

Lowest annual income  
  [[[ 1 15]
  [ 2 15]]]
_______________________________________________________________
Highest annual income  
 [[[199 137]
  [200 137]]]


In [83]:
# task 4 customers with spending score > 75, min annual sal > 35000, age < 45

spagesal = np.where((cusdat[0:,3] > 75) & (cusdat[0:,2] > 35) & (cusdat[0:,1] < 45))
print(f"There are {np.size(spagesal)} customers eligible for discount, they are: \n {cusdat[spagesal]}")

There are 26 customers eligible for discount, they are: 
 [[ 42  24  38  92]
 [124  39  69  91]
 [126  31  70  77]
 [128  40  71  95]
 [136  29  73  88]
 [142  32  75  93]
 [144  32  76  87]
 [146  28  77  97]
 [150  34  78  90]
 [152  39  78  88]
 [154  38  78  76]
 [156  27  78  89]
 [158  30  78  78]
 [162  29  79  83]
 [164  31  81  93]
 [168  33  86  95]
 [174  36  87  92]
 [176  30  88  86]
 [180  35  93  90]
 [182  32  97  86]
 [184  29  98  88]
 [186  30  99  97]
 [190  36 103  85]
 [194  38 113  91]
 [196  35 120  79]
 [200  30 137  83]]


In [93]:
# task 5 new column with discount between 10 and 50%

discount = np.random.randint(10,51,200)
temp = discount.reshape(200,1)
cusdat = np.concatenate((cusdat, temp), axis = 1)
print('After discount is added \n', cusdat)

After discount is added 
 [[  1  19  15 ...  29  41  44]
 [  2  21  15 ...  10  48  24]
 [  3  20  16 ...  14  28  28]
 ...
 [198  32 126 ...  39  14  23]
 [199  32 137 ...  38  49  28]
 [200  30 137 ...  18  46  39]]


In [92]:
# task 6 Customers with discount > 45

cu = cusdat[cusdat[0:, 4] > 45]
print('count of Customers with discount > 45 = ', cusdat[cu].size)
print('Customers with discount > 45 \n', cu)


count of Customers with discount > 45 =  1216
Customers with discount > 45 
 [[  4  23  16  77  46  34  35  35]
 [ 11  67  19  14  47  26  47  40]
 [ 21  35  24  35  48  46  12  27]
 [ 23  46  25   5  48  47  48  47]
 [ 40  20  37  75  50  30  10  26]
 [ 41  65  38  35  47  10  39  14]
 [ 54  59  43  60  46  29  21  18]
 [ 63  67  47  52  49  33  26  29]
 [ 65  63  48  51  46  49  45  12]
 [ 77  45  54  53  47  37  33  31]
 [ 81  57  54  51  47  42  13  44]
 [ 84  46  54  44  49  36  28  15]
 [125  23  70  29  50  20  41  29]
 [178  27  88  69  46  33  25  15]
 [182  32  97  86  47  25  10  15]
 [183  46  98  15  47  37  29  32]
 [184  29  98  88  49  25  30  21]
 [185  41  99  39  50  35  42  45]
 [190  36 103  85  46  21  39  16]]
